builds:
  - binary: cryptography
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
